{{- if .Values.front.ingress.enabled -}}
{{- $svcPort := .Values.front.service.port -}}
{{- $name := include "workadventure.front.name" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $name }}
  labels:
    {{- include "workadventure.labels" . | nindent 4 }}
  {{- with .Values.front.ingress.annotations }}
  annotations:
  {{- if $.Values.basicAuth.user }}
    # type of authentication
    nginx.ingress.kubernetes.io/auth-type: basic
    # name of the secret that contains the user/password definitions
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    # message to display with an appropriate context why the authentication is required
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required.'
  {{- end }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($host = "{{ $.Values.domain }}") {
          return 308 https://play.{{ $.Values.domain }}$request_uri;
      }
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.front.ingress.useNginx}}
  ingressClassName: nginx
  {{- end }}
  {{- if .Values.front.ingress.tls }}
  tls:
    {{- range .Values.front.ingress.tls }}
    - hosts:
        {{- range .hosts }}        
        {{ $fqdn := printf "%s%s" . $.Values.domain -}}
        - {{ $fqdn }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.front.ingress.hosts }}
    {{ $fqdn := printf "%s%s" .host $.Values.domain -}}
    - host: {{ $fqdn }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . | quote}}
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
      {{- end }}
{{- end }}
